apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-application
  labels:
    app: delivery-application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: delivery-application
  template:
    metadata:
      labels:
        app: delivery-application
    spec:
      containers:
      - name: delivery-application
        image: hemanth1337/binance:82
        ports:
        - containerPort: 80
